### ISSUE TITLE
Unhandled Exception: PlatformException(error, The new embedding does not support the old FlutterView., null)

### ISSUE THREAD

**Issue by marcoriesco** [flame-engine/play_games#12]
Testing the app I realized that the popup of the achivements were not shown, this error corrected at the beginning of the installation and configuration of the extension, I removed the line: await PlayGames.setPopupOptions ();

As I realized that the notices for Records and Achivements did not open, I decided to uncomment the line and now brings this error:

`E/flutter (15426): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, The new embedding does not support the old FlutterView., null)
E/flutter (15426): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (15426): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (15426): <asynchronous suspension>
E/flutter (15426): #2      PlayGames.setPopupOptions (package:play_games/play_games.dart:148:10)
E/flutter (15426): #3      GameServices.login (package:gamedabiblia/services/gameservices.dart:21:20)
E/flutter (15426): <asynchronous suspension>
E/flutter (15426): #4      _HomeState._login (package:gamedabiblia/main.dart:69:39)
E/flutter (15426): #5      _HomeState.initState (package:gamedabiblia/main.dart:105:24)
E/flutter (15426): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
E/flutter (15426): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (15426): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (15426): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (15426): #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (15426): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (15426): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (15426): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (15426): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (15426): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (15426): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (15426): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (15426): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (15426): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (15426): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (15426): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (15426): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (15426): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (15426): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (15426): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (15426): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (15426): #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (15426): #28     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter (15426): #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (15426): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (15426): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (15426): #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (15426): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (15426): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (15426): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (15426): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (15426): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (15426): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (15426): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (15426): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (15426): #41     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter (15426): #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (15426): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (15426): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (15426): #45     ComponentElemen`

**Comment by VladyslavBilomeria** [comment]
@marcoriesco
I tried to solve this problem. Here is my [fork](https://github.com/VladyslavBilomeria/play_games.git).
It works for me on Flutter v1.12.13+hotfix.8
This is a temporary solution. It is necessary that the specialist make the correct changes.

WARNING!
I am not a specialist in creating such plugins. The changes I made could accidentally break some functions

**Comment by luanpotter** [comment]
@VladyslavBilomeria I'm glad you were able to fix it! would you like to send a PR so we can merge it?

**Comment by VladyslavBilomeria** [comment]
@luanpotter Done! #16
