### ISSUE TITLE
Removing initial authentication dialog

### ISSUE THREAD

**Issue by jitinder** [flame-engine/play_games#13]
Modern games no longer have a authentication dialog the first time you sign in with GPG. Can there be an option to choose this option?

**Comment by erickzanardo** [comment]
Can't you just call the sign in method upon user interaction?

**Comment by jitinder** [comment]
Calling upon user interaction has no significance in this. 

Whenever the sign-in method is called for the first time in the app, there is a google play services permission dialog shown. This isn't needed as per this:

https://android-developers.googleblog.com/2016/01/play-games-permissions-are-changing-in.html
