### ISSUE TITLE
How to save Ranking and retrieve the profile image and the username?

### ISSUE THREAD

**Issue by d-apps** [flame-engine/play_games#5]
In my game I will only need to save and show the Ranking and I needed to log the user with Google Play Games and retrieve the image and username, do you have any tutorial for this? I couldn't find anything in readme.

This is for my first game made in Flutter.

Thank you.

**Comment by luanpotter** [comment]
What exactly do you mean by ranking? Are you referring to the leaderboards? The first step is to log the user in. For that, there is an extensive tutorial [here](https://github.com/flame-engine/play_games/blob/master/doc/signin.md).

After that you get the username and picture, and then you are able to use the other play games methods, including the ones to submit and show leaderboards.

The example game [crystap](https://github.com/luanpotter/crystap) has lots of functionalities regarding play_games as an example/demo.

Hope this helps :)

**Comment by d-apps** [comment]
It's Leaderboards, I'll follow the game example that you shared. Show leaderboard is the only functionality I need.
Thank you very much!
