### ISSUE TITLE
PlayGames.showLeaderboard concurrent exception

### ISSUE THREAD

**Issue by krizda** [flame-engine/play_games#8]
Oppening  PlayGames.showLeaderboard("") closing and opening again throws exception: "Unhandled Exception: PlatformException(error, signIn/showAchievements/showLeaderboard/saved games/snapshots cannot be used concurrently!, null)"

This does not happen when PlayGames.showAchievements() is called two times

**Comment by luanpotter** [comment]
Thanks for reporting this, @krizda :)

Probably a bug in the showLeaderboard method not cleaning up the transaction (`pendingOperation` variable). Needs further investigating, but should be an easy fix, if you wanna help out.
